### ISSUE TITLE
请求加入导入网易云歌单功能

### ISSUE THREAD

**Issue by CberYellowstone** [enzeberg/tongzhong-music#12]
在[MKOnlineMusicPlayer](https://github.com/mengkunsoft/MKOnlineMusicPlayer)这个仓库中有实现方法
希望开发者能考虑一下

**Comment by CberYellowstone** [comment]
@enzeberg

**Comment by enzeberg** [comment]
@CberYellowstone 暂时弄成这样了，还不完善。欢迎你继续跟我交流，来让这一块更加完善。

**Comment by CberYellowstone** [comment]
> @CberYellowstone 暂时弄成这样了，感觉还存在不少问题（例如接口返回的歌单不完整）。不知道这种获取歌单的方式是不是你想要的那种？
> 
> 欢迎你继续跟我交流，来让这一块更加完善。

感谢开发者能在百忙之中抽空实现这个功能
这个获取方式是我想要的那种
就差歌单完整获取的问题了
[这个项目](https://github.com/metowolf/Meting)提供了完整获取网易云歌单的方法
可以参考一下
