### ISSUE TITLE
只能加三首歌

### ISSUE THREAD

**Issue by gusyang** [enzeberg/tongzhong-music#14]
感谢，非常好的东西。今天发现这个网站使用了一下，发现几个问题

- 只能添加三首歌到我喜欢的音乐，提示添加成功，但是并没有

> 开了两个tab， 一个播放并添加，另一个tab刷新 我的音乐

- 网易的没办法播放

Windows 10, Chrome, 在美国

**Comment by enzeberg** [comment]
@gusyang 感谢反馈！

- 确实存在这个问题，貌似单独添加一首歌时，如果`favoriteSongs`里已经存在相同平台的歌的话，就添加不上了，而如果一次性添加多首是可以的 😂 （列表顶部的添加按钮可以添加当前列表）。这个 bug 我会尽快修复的。
- 网易的可以播放啊，有些不能播放估计是需要 VIP 的。

**Comment by gusyang** [comment]
光速回复啊。
我自己建了歌单是可以加的。
建议在歌单播放的地方添加随机播放的功能

**Comment by enzeberg** [comment]
bug 修好了！

播放器上有“随机播放”模式，你的意思是在列表上加一个“随机播放”的按钮，然后歌曲会在一个临时列表里（不会保存到 localStorage ），是吗？

**Comment by gusyang** [comment]
谢谢。
差不多这个意思吧，我在自己的歌单上面看只有一个播放按钮，是按顺序放的。
