### ISSUE TITLE
歌曲播放错误

### ISSUE THREAD

**Issue by CberYellowstone** [enzeberg/tongzhong-music#17]
例如 RAD8kWIMPS-花火大会
酷我源没问题 
QQ源放不了,直接报错
网易云源比较玄学,是不完整的
版本是018版
[问题复现链接](https://apps.ystone.top:8082/search?keyword=%E8%8A%B1%E7%81%AB%E5%A4%A7%E4%BC%9A)
希望开发者能看看是什么导致的

**Comment by enzeberg** [comment]
这个是它们做的限制，我也无可奈何。😂

**Comment by CberYellowstone** [comment]
> 这个是它们做的限制，我也无可奈何。😂

这个可太难受了
貌似是最近升级了一次接口
